# .github/labeler.yml

version: v1

labels:
  - label: 'enhancement'
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 8 matchers
      title: '^feat:.*'
      title: '^feature:.*'
  - label: 'bug'
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 8 matchers
      title: '^fix:.*'
  - label: 'ospp-2024'
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 8 matchers
      baseBranch: '^ospp-2024/.*'