name: Pull Request Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
      - name: Apply labels based on PR title
        uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
      # - uses: ZeWaka/KeywordLabeler@master
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: "Assign label based on the title"
      #   uses: Bhacaz/label-regex@v2.1
      #   with:
      #     field: title
      #     regex: '([A-Z]+?)-'
      #     lowercase: true
      #     token: ${{ github.token }}
